# Configuração do nVender-REBUILT

# Defina a permissão desejada para cada tipo de venda (definida por padrão como 'nvender.shift' e 'nvender.automatico')
permissao-shift: 'nvender.shift'
permissao-automatico: 'nvender.automatico'
permissao-vender: 'nvender.usar'

# Siga o modelo abaixo de venda
# ALERTA: Lembre-se que este é o preço definido pela quantia de blocos definida na configuração abaixo.
Itens:
    Pedra:
      ID: '1:0'
      Valor: 10.0
      Quantidade: 1 # Quantidade de itens para multiplicar
    Grama:
      ID: '2:0'
      Valor: 25.0
      Quantidade: 2304 # Exemplo de quantidade de itens para todo inventario

Captcha:
    # Alerta: Não insira cores no nome do captcha
    ITEM1:
        Nome: 'Maça'
        ItemID: 260 
        ItemData: 0
    ITEM2:
        Nome: 'Dinamite'
        ItemID: 46
        ItemData: 0
    ITEM3:
        Nome: 'Fornalha'
        ItemID: 61
        ItemData: 0
    ITEM4: 
        Nome: 'Sinalizador'
        ItemID: 138
        ItemData: 0
        
Config:
    # Utilizado para a solução de problemas 
    debug-mode: false
    # Nome do inventário do captcha
    Title-Name: "&8Venda -> Clique no(a) %item%"
    # Caso o captcha abaixo esteja desativado, jogadores poderam
    # vender sem concluir um captcha
    Captcha: false
    # Insira aqui o delay que você deseja para o shift vender [Em segundos]
    # Insira zero para remover o delay 
    DelayShift: 1.0
    # Insira aqui o delay que você deseja para o auto venda [Em segundos]
    # Caso insira um valor menor que 0.5, o valor default será usado:
    DelayAutoVenda: 2.5
    
Multiplicador:
    # Tipos de Multiplicador
    # Valores válidos [grupo,permissao,nenhum]
    # Caso utilize 'grupo', o jogador receberá o multiplicador
    # de acordo com seu grupo.	
    # Caso utilize 'permissao', o jogador receberá o multiplicador
    # de acordo com sua permissao.
    Tipo: 'grupo'
    #
    # Valores iguais a 100% representam todo o valor
    # Exemplos:
    #
    # Item custa 10 coins
    # 100% = 10 coins
    # 50% = 5 coins
    # 200% = 20 coins
    Membro:
        Grupo: 'default'
        Permissao: 'vender.membro'
        Multiplicador: '100%'
    # Neste exemplo, o grupo vip vai receber 2X mais que o membro nas vendas
    Vip:
        Grupo: 'vip'
        Permissao: 'vender.vip'
        Multiplicador: '200%'

Mensagens:
    Sem-Permissao: "&cVocê não tem permissão para executar este comando."
    Configuracao-Recarregada: "&aConfiguração e arquivos de linguagem foram recarregados."
    Captcha-Invalido: "&cO captcha inserido é inválido."
    Vendido-Sucesso: "&aVocê vendeu &7%itens% &aitens por &7$%dinheiro%&a."
    Sem-Itens: "&cVocê não possui itens para serem vendidos."
    Inventario-Vazio: "&cVocê não pode estar com um inventário vazio."
